### ISSUE TITLE
Should we place the new game within Jolt Sphere or Leave it as it's Own Thing?

### ISSUE THREAD

**Issue by Aspenup** [Flame6332/Jolt-Sphere#5]
I think that a new game should be contained within itself without being in the background of Jolt Sphere. We are not sure if a fan base will be large enough to offer enough attention to Jolt Sphere itself and we are not sure of the potential success of Jolt Sphere in the first place. The reason CSGO had a successful run and fan base even though it lacked a story was because it was created by a multimillionaire company that spent more money than we can imagine and was expected to have some amount of success no matter what. We are a team of three developers that haven't even graduated high school yet and are running on a shoestring budget. We may have an edge to other developers who only rely on Steam to get their game out there but how impressive can our fan base actually become? The popularity and revenue of a product vs time and money spent on it is a risk that any business must take, but we should not stretch that risk further than necessary. 
   1. For one, we don't know if Jolt Sphere will succeed in the first place, so it seems like an enormous risk to add in another game into the current one just to target the potential (and I say potential very generously) fan base that might find it. For all we know, it could be so small that nobody ends up finding the game hidden within a game and we end up losing two games instead of one.
   2. The game should be consistent with Jolt Sphere and have a sort of connection to it, but if we did that, we might as well just make it another mini game. In fact, we could, but frankly, we still have a lot to work on in this game before we have a presentable finished product and that should be focused on before we decide to add anything else to it. After all, I'm not even sure if we've completed our list of mini games yet and we are still working on the ones at hand.
   3. If the game isn't relevant to Jolt Sphere in any way, it would make the product seem confusing and not to be taken seriously because like you said earlier, "the game wouldn't know what it wants to be." This new secret game just feels like a fantasy that hasn't been put much thought into (no offense) but it's just a mixture of things that don't make sense. Jolt Sphere isn't a comedy, so it doesn't seem right to have something as random as this in a game about something completely different, and it isn't mysterious, so people aren't looking for hidden surprises. It is just a fun little game for people to compete against each other for fun. I don't know if you want the game to be taken very seriously in gameplay or not, but now a days, for that to happen, there have to be fancy graphics and a budget beyond what we can afford. It doesn't have to be too serious in gameplay but it is vital that it's serious in design. 
  4. Having it be its own game will likely raise up the revenue gained vs the revenue combined from the two in one package idea. It also causes it to have more attention since people will be aware that the people who developed this developed a game before it. That will cause those who haven't played Jolt Sphere to have more trust in our experience since we've already developed a game. The fan base received from Jolt Sphere can be counted on playing this new game as well since they liked what we did before. It will also gain even more fans if we do any more advertising. This culmination of fans will hopefully be more than Jolt Sphere's because of the effect of having a separate game. Not only that, but since Steam has changed the system so that practically any game can get in, they all rely on survival of the fittest now. That means that the only way we will be able to survive is if we have some popularity to begin with. Our game will then be discovered more often because it has more popularity than others. That will snowball and we might even get more than we bargained for (though that might just be a bigger fantasy than having a lot of success through placing a secret game within Jolt Sphere). But, anyway, that's just a theory, a game theory, and I'm tired of typing, and I lost my thought process. Good day to you and I hope I haven't been too harsh or overly cautious; I know I might be clueless about the gaming community on some aspects as well.

**Comment by Youseflapod** [comment]
I vote to place a new game in the menu screen of Jolt Sphere for the existing fan base and to improve the game as a whole without increasing developer costs

**Comment by Aspenup** [comment]
So, then, have we come to an agreement yet for the location of the new game?

**Comment by mjt2000d** [comment]
I'm so confused, can someone tell me about this new game

**Comment by Youseflapod** [comment]
Oh, sorry Mathew, basically, me and Raneem were talking about any future smaller projects after joltsphere, like maybe a short story game or something like that, it's just hypothetical, but we were talking about whether or not we should add any future projects that are kinda hidden in the menu screen that have no correlation to jolt sphere

**Comment by mjt2000d** [comment]
I agree with Raneem and believe we should add it later

**Comment by Youseflapod** [comment]
Ok, so I never mentioned anything about adding any new games now, at minimum, it wouldn't be till after Christmas break and stuff before we considered any new games, also, this choice depends on many unknowns, such as how long the extra game is, like if we wanted to do a short 15 minute heart breaking story, then it would be a waste of time to put it anywhere else but jolt sphere, and it also really relies on what the fan base is like. If the fan base is a serious MLG gaming community like CS:GO, then that's a probable no for any small games, but if the community is super casual and east going, maybe a short story easter egg would be a welcome addition! It really depends on the scale of the game that we would add on, however I really doubt that we would make any large scale games for a while after jolt sphere because we still have to work on updating jolt sphere for a while and it's more fun to do many small projects anyway. And lastly, it realy depends on how we present the game, like if we make it easily accessed and have physics like jolt sphere, then yes it will be 100% confusing for the players, but, if we make it a "super secret" way of getting in for the bigger players, like maybe, on the menu screen, if they do some trick, it fades to black, then fades to a short white text message about why we made the game and put it on jolt sphere, then fades into a nice short and touching nonphysics based game, that would be perfect in my opinion. The secret method ovbiously won't be that secret but it will psychologicaly trick the player into thinking that they're not supposed to be there and that it was put there for the simple reason of letting the world experience the game. Additionally, the dev time would be cut in half becuase we already would have all the framework ready for joltsphere and it would still feel like we were adding stuff to joltsphere, also, any new games would be very difficult to monetize, so it would cost 100 bucks for no money in return, while if we put it on joltsphere, we could ado in a collectible hat or something for the balls that references the hidden game! 
Anyway though, in the end, this decision will depend on the future so we should probably just postpone any final decisions until then, I'm probably gonna close this issue in a couple days.
